WebApplication1/TestApplication1/Models/AuthorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TestApplication1.Models
{
    public class AuthorModel
    {
        public AuthorModel()
        {
            Books = new List<Book>();
        }
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public List<Book> Books { get; set; }
    }

    public class Book
    {
       [Key]
        public int id { get; set; }
        public string Title { get; set; }
        public DateTime PublishedDate { get; set; }
        [NotMapped]
        public string Radiobutton { get; set; }

    }
}

WebApplication1/TestApplication1/Controllers/AuthorModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestApplication1.Models;

namespace TestApplication1.Controllers
{
    public class AuthorModelsController : Controller
    {
        private TestApplication1Context db = new TestApplication1Context();

        // GET: AuthorModels
        public ActionResult Index()
        {
            db.AuthorModels.Include("Books").ToList();
            return View(db.AuthorModels.ToList());
        }

        // GET: AuthorModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorModel authorModel = db.AuthorModels.Find(id);
           // authorModel.Books = db.AuthorModels.Find(id);
            if (authorModel == null)
            {
                return HttpNotFound();
            }
            return View(authorModel);
        }
        public class AuthorViewModel
        {
            public int Id { get; set; }
            public string Name { get; set; }
 
        }
        // GET: AuthorModels/Create
        public ActionResult Create(AuthorModel authorModel)
        {
            AuthorViewModel vm = new AuthorViewModel();
            //vm.Name = "111";
             return View();
            //return new RedirectResult(Url.Action("PartialView", "Home", vm.Name));
           // return RedirectToAction("PartialView", "Home", new { selectedRegionName= vm.Name });
        }

        // POST: AuthorModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Name")] AuthorModel authorModel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        //AuthorModel model = new AuthorModel();
        //        //model.Name=authorModel.Name;
        //        db.AuthorModels.Add(authorModel);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(authorModel);
        //}

        // GET: AuthorModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorModel authorModel = db.AuthorModels.Find(id);
            // authorModel.Books = db.AuthorModels.Include("Books");
            if (authorModel == null)
            {
                return HttpNotFound();
            }
            return View(authorModel);
        }

        // POST: AuthorModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] AuthorModel authorModel)
        {
            
            if (ModelState.IsValid)
            {
                #region 执行成功 新模型修改旧模型
                //var entity = db.AuthorModels.Find(authorModel.Id);
                //db.Entry(entity).CurrentValues.SetValues(authorModel);
                //db.SaveChanges();
                #endregion

                db.Entry(authorModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
                //return PartialView("~/Views/Home2/_SideBar.cshtml");
            }
            return View(authorModel);
        }

        // GET: AuthorModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorModel authorModel = db.AuthorModels.Find(id);
            if (authorModel == null)
            {
                return HttpNotFound();
            }
            return View(authorModel);
        }

        // POST: AuthorModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AuthorModel authorModel = db.AuthorModels.Find(id);
            db.AuthorModels.Remove(authorModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/TestApplication1/Views/AuthorModels/Create.cshtml
@model TestApplication1.Models.AuthorModel
@*@model TestApplication1.Controllers.AuthorModelsController.AuthorViewModel*@

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AuthorModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/TestApplication1/Views/AuthorModels/Delete.cshtml
@model TestApplication1.Models.AuthorModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AuthorModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/TestApplication1/Views/AuthorModels/Details.cshtml
@model TestApplication1.Models.AuthorModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AuthorModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/TestApplication1/Views/AuthorModels/Edit.cshtml
@model TestApplication1.Models.AuthorModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>AuthorModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>AuthorModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/TestApplication1/Views/AuthorModels/Index.cshtml
@model IEnumerable<TestApplication1.Models.AuthorModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
            @Html.ActionLink("Create New", "Create")
        </p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {

        if (@item.Name == "au2")
        {
            <tr style="background-color:red;">
                <td>@item.Name</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
        else
        {
            <tr style="background-color:blue;">
                <td>@item.Name</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
                }
            </tr>

        }
    }

        </table>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>



    <a href="@Url.Action("Create", "AuthorModels")" target="_blank">Click me</a>

@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.Books[0].id)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.Books[0].Title)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.Books[0].PublishedDate)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {


        foreach (var book in item.Books)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => book.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => book.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => book.PublishedDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    }

    </table>*@