WebApplication1/TestApplication1/Controllers/Home2Controller.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TestApplication1.Models;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net.Mail;
using System.Net;
using System.Text.RegularExpressions;
using System.Data.Entity.Infrastructure;
using System.Xml.Schema;
using System.Xml.Linq;
using System.Reflection;
using System.Data.Entity.Core.Objects;
using PdfSharp;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using System.Text;
using System.Globalization;
using MySql.Data.MySqlClient;
using Rotativa;
using LINQtoCSV;
using Microsoft.Security.Application;
using Aspose.Words;
using System.Web.Caching;
using System.Web.Configuration;

namespace TestApplication1.Controllers
{
    public class Home2Controller : Controller
    {
        private TestApplication1Context db = new TestApplication1Context();

        #region 获取日期之间的总月份 Calculate the number of months between two dates with C#
        public static int GetMonthDifference(DateTime startDate, DateTime endDate)
        {
            int monthsApart = 12 * (startDate.Year - endDate.Year) + startDate.Month - endDate.Month;
            return Math.Abs(monthsApart);//返回数的绝对值。
        }
        #endregion     
        // GET: Home2
        public ActionResult Index()
        {         
          
            //var assignments = from s in db.book2s.Include(b => b.author2)
            //                  where s.Title == "t1"
            //                  select s;

            #region https://forums.asp.net/t/2149906.aspx
            ////string nowdate = DateTime.Now.ToString("M/d/yyyy HH:mm:ss");
            ////DateTime nowdate2 = Convert.ToDateTime(nowdate);
            //DateTime dt = Convert.ToDateTime("12/4/2018 13:00:00");
            ////DateTime dat = new DateTime(2015, 1, 6);
            //// dat.AddMonths(1).ToString("d");
            //DateTime oneMonthAgo = DateTime.Now.AddMonths(1);
            ////        int days = DateTime.DaysInMonth(oneMonthAgo.Year, oneMonthAgo.Month);
            ////        var list=Enumerable.Range(1, DateTime.DaysInMonth(oneMonthAgo.Year, oneMonthAgo.Month)).Select(day =>
            ////new DateTime(oneMonthAgo.Year, oneMonthAgo.Month, day)).ToList();

            //var selectedDates = new List<DateTime>();
            //var selectedmins = new List<DateTime>();

            ////for (var date = nowdate2; date <= oneMonthAgo; date = date.AddDays(1))
            ////{
            ////    selectedDates.Add(date);
            ////}

            //for (var date = dt; date <= oneMonthAgo; date = date.AddMinutes(15))
            //{
            //    if ((date.DayOfWeek == DayOfWeek.Monday && date.Hour >= 10 && date.Hour < 12) || (date.DayOfWeek == DayOfWeek.Tuesday && date.Hour >= 12 && date.Hour < 14) || (date.DayOfWeek == DayOfWeek.Thursday && date.Hour >= 10 && date.Hour < 14))
            //    {
            //        selectedmins.Add(date);
            //    }
            //    else
            //    {
            //        continue;

            //    }
            //}

            ////var listb = selectedDates.Where(_ => _.DayOfWeek == DayOfWeek.Monday || _.DayOfWeek == DayOfWeek.Tuesday || _.DayOfWeek == DayOfWeek.Thursday).ToList();

            ////TimeSpan timeSpan = Convert.ToDateTime("10:00") - Convert.ToDateTime("12:00");
            ////TimeSpan ts = oneMonthAgo.Subtract(nowdate2).Duration();
            ///
            #endregion
            #region 获取日期之间的总月份 Calculate the number of months between two dates with C#
            //DateTime now = DateTime.UtcNow;
            //DateTime past = now.AddMonths(-5);
            //int monthDiff = GetMonthDifference(now, past);
            #endregion

            return View();
        }

        #region  checkbox 
        public class Like
        {
            public int Id { get; set; }
            public string Info { get; set; }
            public DateTime PostedOn { get; set; }
        }
        public class Comment
        {
            public int Id { get; set; }
            public string Info { get; set; }
            public DateTime PostedOn { get; set; }
        }


        // GET: Home/Create
        public ActionResult Create()
        {
            #region Union
            //DateTime xx = DateTime.ParseExact("14/11/2018", "dd/MM/yyyy", CultureInfo.InvariantCulture);
            //DateTime date = DateTime.ParseExact("14/11/2018", "dd/MM/yyyy", null);
            //List<Like> Likes = new List<Like>()
            // {
            //     new Like(){Id=1,Info="A", PostedOn=DateTime.ParseExact("14/11/2018", "dd/MM/yyyy", null) },
            //     new Like(){Id=2,Info="B", PostedOn=DateTime.ParseExact("17/11/2018", "dd/MM/yyyy", null) },
            //     new Like(){Id=1,Info="C", PostedOn=DateTime.ParseExact("18/11/2018", "dd/MM/yyyy", null) },
            // };

            //List<Comment> Comments = new List<Comment>()
            // {
            //     new Comment(){Id=1,Info="D", PostedOn=DateTime.ParseExact("15/11/2018", "dd/MM/yyyy", null) },
            //     new Comment(){Id=2,Info="E", PostedOn=DateTime.ParseExact("16/11/2018", "dd/MM/yyyy", null) },
            //     new Comment(){Id=1,Info="F", PostedOn=DateTime.ParseExact("19/11/2018", "dd/MM/yyyy", null) },
            // };
            //var unionlist = ((from like in Likes
            //                  select new Comment
            //                  {
            //                      Id = like.Id,
            //                      Info = like.Info,
            //                      PostedOn = like.PostedOn
            //                  })
            //                           .Union(from comment in Comments
            //                                  select comment)).OrderBy(_ => _.PostedOn).ToList();
            #endregion https://forums.asp.net/t/2150269.aspx
            var list = db.Student121s.Include(_ => _.Address).ToList();
            var list2 = db.StudentAddress121s.Include(_ => _.Student).ToList();

            return View();
        }

        //POST: Home/Create

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(List<expert> model)
        //{
        //    //  if (ModelState.IsValid)
        //    {

        //        //string strExpertise = string.Empty;

        //        //db.Entry(model).Property("preference").CurrentValue = preference;



        //        db.experts.Add(model);
        //        try
        //        {
        //            db.SaveChanges();
        //            return RedirectToAction("Confirmation");
        //        }
        //        catch (Exception ex)
        //        {
        //            ex.ToString();
        //            return View(model);
        //        }
        //    }


        //}
        public ActionResult Confirmation()
        {
            ViewData["Message"] = "Thank you for submitting the information form!";
            return View();
        }
        #endregion


        public class MessagesVM
        {
            public int RMAID { get; set; }
            public string MSG { get; set; }

            public string MSGType { get; set; }

        }

        public ActionResult Partial_Index()
        {
            #region XSS AntiXSS 从html中删除所有脚本和非标准元素，从而使用户键入的html安全。https://forums.asp.net/t/2150613.aspx
            //ViewBag.query = "<a href='#' id='site' class='btn' data-content='{&quot;RowId&quot;:714886,&quot;SequenceNumber&quot;:1,&quot;Order&quot;:0}' data-assettypeid='1' onclick='ECL.RequestButton(this); return false;'>Sample</a>";
            //ViewBag.query2 = "<a href='#' id='site' class='btn' data-content='111' data-assettypeid='1' onclick='ECL.RequestButton(this); return false;'>Sample</a>";
            //var url = "<a href="http://search.msn.com/results.aspx?q=[Untrusted-input]">Click Here!</a>";
            //string safeHtml = Microsoft.Security.Application.Sanitizer.GetSafeHtml(ViewBag.query2);

            //var html = "<a href="#" onclick="alert();" data-content='111'>aaaaaaaaa</a>javascript<P><IMG SRC=javascript:alert('XSS')><javascript>alert('a')</javascript><IMG src="abc.jpg"><IMG><P>Test</P>";

            //string safeHtml2 = Microsoft.Security.Application.Sanitizer.GetSafeHtml(html);
            //string Name = AntiXss.HtmlEncode(url);
            #endregion
            ViewData["Message"] = "Thank you for submitting the information form!";
            //Session["anoterText"] = "Going to abandon";//与Session_End有关，如果注释掉不能进入Session_End
            //Session.Abandon();
            return View();
        }

        //[ChildActionOnly]
        public ActionResult GetMessages()
        {

            List<MessagesVM> query = (from RB in db.Charters

                                      where RB.CharterID == 4

                                      select new MessagesVM
                                      {
                                          RMAID = RB.CharterID,
                                          MSG = RB.CharterSchoolDepartment,
                                          MSGType = RB.CharterIdentifierString


                                      }).ToList();

            return PartialView("_GetMessages", query);
        }
        public JsonResult UpdateMSGStatus(int IDMSG, string ChangeStu)
        {
            var list = new List<MessagesVM>
            {
                new MessagesVM{MSG="Apple2",RMAID=1,MSGType="tApple2"},
                new MessagesVM{MSG="Banana",RMAID=2,MSGType="tBanana"},

WebApplication1/TestApplication1/Views/Home2/Chart_Index.cshtml
@{
    ViewBag.Title = "Chart_Index";
}

<h2>Chart_Index</h2>

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <table>
            <tr>
                <td>
                    <img src="@Url.Action("CreateBar")" alt="Bar Chart using MVC" />
                </td>
                <td>
                    <img src="@Url.Action("CreatePie")" alt="Pie Chart using MVC" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <img src="@Url.Action("CreateLine")" alt="Line Chart using MVC" />
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <img src="@Url.Action("ElecMechLogs")" alt="Line Chart using MVC" />
                </td>
            </tr>
        </table>


    </div>

    <img src="@Url.Action("ElecMechLogs", "Home2",new {aa="1" })"id="imageID" width="500" alt="Maintenance Chart" />

</body>
</html>

WebApplication1/TestApplication1/Views/Home2/Create.cshtml
@model TestApplication1.Models.expert
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@*@using (Html.BeginForm("Create", "Home2", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group" id="myCheckbox">
            @Html.LabelFor(model => model.preference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="checkbox" class="checkBox" name="preference" value="Radio" /> Radio
                <input type="checkbox" class="checkBox" name="preference" value="Print" />Print
                <input type="checkbox" class="checkBox" name="preference" value="TV" /> TV
                @Html.ValidationMessageFor(model => model.preference, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" id="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}*@

<li><a href="@Url.Action("Index", "Home2", new { @id = 1 })"><span class="next">School</span></a></li>

<li><a href="/Home2?id =1"><span class="next">School</span></a></li>
@*<script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>*@

WebApplication1/TestApplication1/Views/Home2/Gallery_Create.cshtml
@{
    ViewBag.Title = "Gallery_Create";
}

<h2>Gallery_Create</h2>
@using (Html.BeginForm("Gallery_Create2", "Home2", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 

    <div id="table-board" class="site-main" role="main">
        <!-- Title -->
        <input id="title" type="text"
               class="form-control form-control-lg"
               placeholder="제목: 25자 이내 텍스트를 입력하세요."
               style="margin-bottom:30px"
               required>
        <small id="title"></small>

        <!-- summernote 영역 -->
        <div id="summernote" class=""></div>

        <!-- Thumnail -->
        <div>
            <label for="attachFile">파일첨부</label>
            <input type="file"
                   id="thumnail"
                   placeholder="대표 이미지를 첨부하세요."
                   accept="image/gif, image/jpeg, image/png"
                   onchange="readURL(this);" name="file2"> 
        </div>

        <div class="create-button">
            <button id="btnSubmit" @*onclick="dosubmit()"*@ type="submit" class="col align-self-center btn btn-primary" />저장
            <button id="btnCancel" onclick="goBack()" class="col-md-auto btn btn-primary">취소</button>
        </div>
    </div>
    }

@section scripts{
    <script>
        $(document).ready(function () {

            console.log("included this page");

            $('#summernote').summernote({
                placeholder: "내용을 입력하세요.",
                tabsize: 2,
                height: 400,
                minHeight: 400,
                maxHeight: null
            });

            //$('#btnSubmit').on('click', function () {
            //    var markupStr = $('#summernote').summernote('code');
            //    var data = new Object();
            //    data.title = $("#title").val();
            //    data.contents = encodeURI(markupStr);
            //    data.thumnail = $('#thumnail').val();
            //    console.log("thumnail -> " + data.thumnail);
            //    if (isValid(data)) submit(data);
            //});


            function isValid(param) {
                //Null Check
                if (!validation.NullCheck(param.title)) {
                    alert("제목을 입력하세요."); return false;
                }
                if (param.title.length > 25) {
                    alert("제목은 25자 이내로 작성하세요."); return false;
                }
                if ($('#summernote').summernote('isEmpty')) {
                    alert('내용을 입력하세요.'); return false;
                }
                if (!validation.NullCheck(param.thumnail)) {
                    alert("대표이미지를 첨부하세요.");
                    return false;
                }

                return true;
            }
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    //$('#falseinput').attr('src', e.target.result);
                    $('#thumnail').val(e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        function dosubmit() {
            var data = $('#thumnail').val();
            //var file_data = $("#thumnail").prop("files")[0];
            //var form_data = new FormData();
            //form_data.append("file", file_data);
            $.ajax({
                type: "post",
                url: "/Home2/Gallery_Create2",
                data: {
                    "THUMNAIL": data
                },
                //data: form_data,
                dataType: "json",
                error: function () {
                    alert("시스템 오류입니다.");
                },
                success: function (data) {
                    alert(data.message);
                    $(location).attr("href", "Home2/Gallery");
                }

            });
        }
    </script>
}

WebApplication1/TestApplication1/Views/Home2/OutputCache1.cshtml
@{
    ViewBag.Title = "OutputCache1";

    var tempDataUserPersist = TempData["User"];
    TempData.Keep("User");
}
<h2>OutputCache1</h2>
@ViewBag.CurrentTime
<span id="aa"></span>

<span id="Knob1"></span>
<span id="Knob2"></span>
<span id="Knob3"></span>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

@section scripts{
    <script>

    $(function () {
        var row = $("<a title=Edit href='@Url.Action("OutputCache2", "Home2", new { id ="33" })'>Edit</a>");
        $("#aa").append(row);


    })

        @*setInterval(function () {  //https://forums.asp.net/t/2149730.aspx
        var x =  @TestApplication1.Controllers.Home2Controller.Globals.Variable1
        var y = @TestApplication1.Controllers.Home2Controller.Globals.Variable2;
        var z = @TestApplication1.Controllers.Home2Controller.Globals.Variable3;
        $("#Knob1").append(y);
        $("#Knob2").append(z);
        $("#Knob3").append(x);
    },5000);*@
    </script>
}

WebApplication1/TestApplication1/Views/Home2/ProcessCreateRMA.cshtml
@model List<TestApplication1.Controllers.Home2Controller.CreateRMAVM>
@{
    ViewBag.Title = "ProcessCreateRMA";
}

<h2>ProcessCreateRMA</h2>

@*<form name="add_rma" id="add_rma">*@
@using (Html.BeginForm("ProcessCreateRMA", "Home2", FormMethod.Post, new { @id = "add_rma" }))
{
    <table id='tbhold' class="table">
        <thead>
            <tr>
                <th>Varenummer</th>
                <th>Serienummer</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <div class="col-md-8">
                        <input type="text" name="CreateRMAVM[0].Varenummer" id="Varenummer" class="form-control" />

                    </div>
                </td>
                <td>
                    <div class="col-md-8">
                        <input type="text" name="CreateRMAVM[0].Serienummer" id="Serienummer" class="form-control" />
                    </div>
                </td>
                <td>
                    <button type="button" name="add" id="add" class="btn btn-success">Add More</button>
                </td>
        </tbody>
    </table>
    <input type="button" name="submit" id="submit" value="Submit" />
    @*</form>*@
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
@section scripts{

    <script>

         $(document).ready(function () {
        //Add input field
        var i = 0;
        $("#add").click(function (e) {
            i++;
            e.preventDefault();
            $("#tbhold").append('<tr id="row' + i + '"><td><div class="col-md-8"><input type="text" name="CreateRMAVM[' + i + '].Varenummer"  class="form-control" /></div></td><td><div class="col-md-8"><input type="text" name="CreateRMAVM[' + i + '].Serienummer"  class="form-control" /></div></td><td><button type="button" class="btn btn-danger btn_remove"  name="remove">X</button></td></tr>');

        });

        //Remove input field
        $(document).on('click', '.btn_remove', function () {
            var button_id = $(this).attr("id");
            $("#row" + button_id + '').remove();
        });

    //Save to db by click
    $("#submit").click(function (e) {
        e.preventDefault();


        ////var data = $("#add_rma").serializeArray();
        //var formData = {};
        //var list = [];
        ////for (var i = 0; i < data.length; i++) {
        ////    formData[data[i].Varenummer] = data[i].Serienummer;
        ////}
        //var data = decodeURIComponent($('#add_rma').serialize(), true);
        //data.split('&').forEach(function (param) {
        //    param = param.split('=');
        //    var name = param[0],
        //        val = param[1];
        //    formData.CreateRMAVM[0].Varenummer = val;
        //   // $('#fs [name=' + name + ']').val(val);
        //    list.push(formData);
        //})

        $.ajax({
          type: 'POST',
          url: '@Url.Action("ProcessCreateRMA", "Home2")',
            dataType: 'json',
            //contentType: 'application/json',
            data: decodeURIComponent($('#add_rma').serialize(), true),
            //data: $(form).serializeArray().filter(function (r) {        https://forums.asp.net/t/2158727.aspx?Capture+Form+Elements+Inside+foreach+loop case
            //return ["UserName", "BlogId", "Comment"].indexOf(r.name) < 0
        }),
            //data: data,

            success: function (CreateRMA) {
                console.log(CreateRMA);
            },
            error: function () {
            console.log('something went wrong - debug it!');
            }
        });
     });


 });
    </script>
}

WebApplication1/TestApplication1/Views/Home2/RealTimeReports.cshtml
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "RealTimeReports";
}

<h2>RealTimeReports</h2>

@{ Html.RenderPartial("_ExcelDownloadLink", new ViewDataDictionary { { "model", "Report" } }); }

<div class="table-responsive text-center">
    <table class="table table-bordered">
        @*@Html.Partial("_ShowReports_tr", new Ranking24.Models.Report())*@

        <tbody class="data">

            <tr>
                <td>
                    11111111111
                </td>
                <td>
                    111111
                </td>
                <td>
                    11111111111111
                </td>
                <td>
                    111111
                </td>
                <td>
                    <p class="badge">
                        1111
                    </p>
                </td>
                <td>
                    11111111
                </td>
                <td>
                    111111
                </td>
                <td>
                    111111
                </td>
            </tr>

        </tbody>


    </table>
    @Html.PagedListPager((IPagedList)ViewBag.profilelists, Page => Url.Action("_ShowReports", new { Page, IsRealTime = true }))
</div>

WebApplication1/TestApplication1/Views/Home2/UploadIm_Index.cshtml
@{
        Layout = null;
        ViewBag.Title = "UploadIm";
    }

    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>

        <script src="http://localhost:51095/Scripts/jquery-1.10.2.min.js"></script>
    </head>
    <body>
        <div>
            <input type="file" name="browseImage" id="browseImage" onchange="picToBlob()" />
            <canvas id='canvas'></canvas>
            <img id="imgPhoto" />
        </div>

        <script>

              var canvas = document.getElementById('canvas');
            var input = document.getElementById('browseImage');
         var preview = document.getElementById('imgPhoto');

            function picToBlob() {

            canvas.renderImage(input.files[0]);

        }

            HTMLCanvasElement.prototype.renderImage = function (blob) {
             var ctx = this.getContext('2d');
            var img = new Image();
             var width = 200;
            var height = 160;
            img.onload = function () {
                 //ctx.drawImage(img, 0, 0)
                 ctx.drawImage(img, 0, 0, width, height);
            }

            img.src = URL.createObjectURL(blob);
            preview.setAttribute('src', URL.createObjectURL(blob));



            //Saving
                var formdata = new FormData(); //FormData object
                //add form data
                formdata.append(blob.name, blob);

            $.ajax({
                type: 'POST',
                url: '@Url.Action("UploadIm", "Home2")',
                data: formdata,
                processData: false,  // tell jQuery not to process the data
                contentType: false,  // tell jQuery not to set contentType
                 success: function (msg) {
                    alert("Done, Picture Uploaded.");
                }
            });
            };

        </script>

    </body>
    </html>

@*<div>
    <input type="file" name="browseImage" id="browseImage" onchange="picToBlob()" multiple/>
    <canvas id='canvas'></canvas>
    <img id="imgPhoto" />
</div>
<script src="http://localhost:51095/Scripts/jquery-1.10.2.min.js"></script>
<script>
    var canvas = document.getElementById('canvas');
    var input = document.getElementById('browseImage');
    var preview = document.getElementById('imgPhoto');

    function picToBlob() {
        canvas.renderImage(input.files[0]);
    }

    HTMLCanvasElement.prototype.renderImage = function (blob) {

        var ctx = this.getContext('2d');
        var img = new Image();
        var width = 200;
        var height = 160;
        img.onload = function () {
            //ctx.drawImage(img, 0, 0)
            ctx.drawImage(img, 0, 0, width, height);
        }

        img.src = URL.createObjectURL(blob);
        preview.setAttribute('src', URL.createObjectURL(blob));



        //Saving
        var Pic = document.getElementById("canvas").toDataURL("image/jpg");
        Pic = Pic.replace(/^data:image\/(png|jpg);base64,/, "");



        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadIm", "Home2")',
            data: '{ "imageData" : "' + Pic + '" }',
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            success: function (msg) {
                alert("Done, Picture Uploaded.");
            }
        });
    };

    input.addEventListener('change', picToBlob, false);
</script>*@

WebApplication1/TestApplication1/Views/Home2/_ExcelDownloadLink.cshtml
@Html.ActionLink("خروجی اکسل", "Download", "ExcleDownload",new { @class = "btn btn-info btn-block font-homa" })

WebApplication1/TestApplication1/Views/Home2/_GetMessages.cshtml
@model List<TestApplication1.Controllers.Home2Controller.MessagesVM>
<a class="btnChangestu">11111</a>
<input type="hidden" name="ChangeStu" id="ChangeStu" value="læst besked" />
@section scripts{
    <script>

    $(document).ready(function () {
     
        //$('.btnChangestu').click(function () {

            var id = $(this).attr('id');
            var ChangeStu = $("#ChangeStu").val();

            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateMSGStatus", "Home2")',
                data: {
                    IDMSG: 3,
                    ChangeStu: "xxx"
                },
                dataType: 'json',
                success: function (result) {

                    if (!$.trim(result)) {

                        console.log("error");
                    } else {

                        result.MSGType = ChangeStu;
                        result.ID = id;

                        console.log("Ok");
                    }

                },
                error: function () {
                    console.log('something went wrong - debug it!');
                }
            })

        //});


    });
    </script>
}

WebApplication1/TestApplication1/Views/Home2/checkbox_string.cshtml
@{
    ViewBag.Title = "checkbox_string";
}

<h2>checkbox_string</h2>
@using (Html.BeginForm("checkbox_string", "Home2"))
{
    <div class="col-md-6">

        <table class="table">
            <thead>
                <tr>
                    <th>
                        Depot
                    </th>
                    <th>

                        <input type="checkbox" id="DepotCheck" value="SelectAll" />
                        <label>SelectAll</label>
                    </th>
                    <th>

                        <input type="checkbox" id="Defaultcheck" value="SelectAll" />
                        <label>SelectAll</label>
                    </th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td>

                        111

                    </td>

                    <td>
                        <input type="checkbox" name="DepotLink" value="1" asp-for="checkboxDepotLink" />
                    </td>
                    <td>
                        <input type="checkbox" asp-for="checkboxDefaultDepot" />
                    </td>
                </tr>
                <tr>
                    <td>

                        222

                    </td>

                    <td>
                        <input type="checkbox" name="DepotLink" value="2" asp-for="checkboxDepotLink" />
                    </td>
                    <td>
                        <input type="checkbox" asp-for="checkboxDefaultDepot" />
                    </td>
                </tr>

            </tbody>

        </table>
        <div class="center-block  col-sm-6">
            <button type="submit" class="btn btn-primary form-control">Save</button>
        </div>

    </div>
}


<a class="fa fa-thumbs-up" onclick="return AreYouSureFunction(this)"
   href="@Url.Action("Like",new { controller = "Home2" })">
    111
</a>



        @section scripts{
            <script>
                $("#DepotCheck").click(function () {
                    //$('input:checkbox').not(this).prop('checked', this.checked);
                    $("input[asp-for='checkboxDepotLink']").prop('checked', this.checked);
                });

                function AreYouSureFunction(source) {

                    //Prompt for confirmation
                    //Your AJAX call that corresponds with the href attribute of your link
                    $.ajax({
                        url: source.href,
                    }).done(function () {
                       // alert(11);
                        //document.location.reload();
                        console.log(111);


                    });
                    //This prevents the default behavior of the actual link (it will hit your controller action)
                    return false;
                }
            </script>
        }