WebApplication1/TestApplication1/Models/author2.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestApplication1.Models
{
    public class CantbothExistValidatorAttribute : ValidationAttribute
    {

        //private readonly int _maxWords;
        //public CantbothExistValidatorAttribute(string maxWords) : base("{0}字符太多")
        //{
        //    _maxWords = maxWords;
        //}
        //public string Compare1 { get; set; }
        // public int MaxStringLength { get; set; }

        //private readonly string _comparisonProperty;

        //public CantbothExistValidator(string comparisonProperty)
        //{
        //    _comparisonProperty = comparisonProperty;
        //}

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var model = (Models.author2)validationContext.ObjectInstance;
            // DateTime EndDate = Convert.ToDateTime(model.Compare2);
           // DateTime StartDate = Convert.ToDateTime(value);

            //if (model.Compare2 != null)
            //{
                return new ValidationResult
                    ("You can only enter either Production Number or Production Name, you can not enter both");
            //}
            //else
            //{
            //    return ValidationResult.Success;
            //}
        }
    }

    public class DateLessThanAttribute : ValidationAttribute
    {
        private readonly int _comparisonProperty;

        public DateLessThanAttribute(int comparisonProperty)
        {
            _comparisonProperty = comparisonProperty;
        }

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            ErrorMessage = ErrorMessageString;
            var currentValue = (int)value;

            //var property = validationContext.ObjectType.GetProperty(_comparisonProperty);

            //if (property == null)
                throw new ArgumentException("Property with this name not found");

            //var comparisonValue = (DateTime)property.GetValue(validationContext.ObjectInstance);

            //if (currentValue > comparisonValue)
                return new ValidationResult(ErrorMessage);

            return ValidationResult.Success;
        }   
    }

    public class author2
    {
        public author2()
        {
            book2 = new List<book2>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //自增
        public Guid Author_id { get; set; }
        [CantbothExistValidator]
        public string Name { get; set; }
        public virtual List<book2> book2 { get; set; }//virtual为后加不需要迁移，加了之后可以懒加载
        //private string _Compare1;
        //[CantbothExistValidator]
        //[DateLessThan(50, ErrorMessage = "Not valid")]
        public string Compare1 { get; set; }
        //{
        // get { return _Compare1; }
        // set 
        // {
        //     Validator.ValidateProperty(value, new ValidationContext(this, null, null) { MemberName = "Compare1" });
        //     if (string.IsNullOrEmpty(value))
        //     {
        //         throw new Exception("用户名不能为空.");
        //     }
        //        _Compare1 = value; 
        // }
        //[CantbothExistValidator]
        public string Compare2 { get; set; }
    }




}

WebApplication1/TestApplication1/Controllers/author2Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestApplication1.Models;

namespace TestApplication1.Controllers
{
    public class author2Controller : Controller
    {//https://www.codeproject.com/Tips/766214/List-Model-Binding-in-MVC
        //https://forums.asp.net/p/2148051/6234195.aspx?Re+How+to+Bind+SQL+foreign+key+column+to+dropdown+in+MVC+
        private TestApplication1Context db = new TestApplication1Context();

        // GET: author2
        public ActionResult Index()
        {
            ////list3.GroupBy(s => new { s.Text, s.keyword }, (key, group) => new { GroupName = key, Items = group.ToList() })
            //var onelist = db.author2s.ToList();
            //var manylist = db.book2s.ToList();
            ////onelist.GroupBy(s => new { s.Text, s.keyword }, (key, group) => new { GroupName = key, Items = group.ToList() })
            ////onelist.GroupBy(s=>s.Name,(key,goup)=>new{GroupName=key,Items=goup.ToList()})

            //onelist.GroupBy(s => s.book2.GroupBy(p => p.Author_id));
            //manylist.GroupBy(s => new { s.Title, s.Publisher }, (key, group) => new { GroupName = key, Items = group.ToList() });

            //var lresult7 = db.author2s
            //   .Join(db.book2s
            //      , orderdetail => orderdetail.Author_id
            //      , order => order.Author_id
            //      , (orderdetail, order) => new
            //      {
            //          order,
            //          orderdetail
            //      }).GroupBy(od => new
            //      {
            //          od.orderdetail.Author_id,
            //          od.order.Title
            //      })
            //      .OrderBy(d => d.Key.Title)
            //      .Select(grp => new
            //      {
            //          OrderNo = grp.Key.Title
            //      });
            
            return View(db.author2s.ToList());
        }

        // GET: author2/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            author2 author2 = db.author2s.Find(id);
            if (author2 == null)
            {
                return HttpNotFound();
            }
            return View(author2);
        }

        // GET: author2/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: author2/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Author_id,Name")] author2 author2)
        {

            if (ModelState.IsValid)
            {
                author2.Author_id = Guid.NewGuid();
                db.author2s.Add(author2);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author2);
        }

        // GET: author2/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            author2 author2 = db.author2s.Find(id);
            if (author2 == null)
            {
                return HttpNotFound();
            }
            return View(author2);
        }

        public JsonResult UpdateNtf(int? id, string status)
        {

      
            return Json(11, JsonRequestBehavior.AllowGet);

        }

        // POST: author2/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Author_id,Name")] author2 author2)
        {
            
                if (ModelState.IsValid)
                {
                db.Entry(author2).State = EntityState.Modified;
                db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else {
                var msg = string.Empty;
                foreach (var value in ModelState.Values)//https://forums.asp.net/p/2148616/6236661.aspx?Re+Html+TextAreaFor+control+return+Null+exception+for+invalid+ModelState+in+MVC+5
                {
                    if (value.Errors.Count > 0)
                    {
                        foreach (var error in value.Errors)
                        {
                            msg = msg + error.ErrorMessage;
                        }
                    }
                }
                ModelState.AddModelError(string.Empty, msg);//@Html.ValidationSummary

            }

            return View(author2);
        }

        // GET: author2/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            author2 author2 = db.author2s.Find(id);
            if (author2 == null)
            {
                return HttpNotFound();
            }
            return View(author2);
        }

        // POST: author2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            author2 author2 = db.author2s.Find(id);
            db.author2s.Remove(author2);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/TestApplication1/Views/author2/Create.cshtml
@model TestApplication1.Models.author2

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>author2</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/TestApplication1/Views/author2/Delete.cshtml
@model TestApplication1.Models.author2

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>author2</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/TestApplication1/Views/author2/Details.cshtml
@model TestApplication1.Models.author2

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>author2</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Author_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/TestApplication1/Views/author2/Edit.cshtml
@model TestApplication1.Models.author2

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>author2</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Author_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, "--Select Province--", new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })*@
            </div>
        </div>


        ____________________________________________________________

        @*<div class="form-group">
            @Html.LabelFor(model => model.Compare1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Compare1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Compare1, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
                @Html.LabelFor(model => model.Compare2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Compare2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Compare2, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>


    </div>
}
<button data-on="ON" data-off="OFF" data-id="@Model.Author_id" class="switch-label">111</button>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


@section scripts{
    <script>
     $(document).ready(function () {

         $('.switch-label').click(function () {

             var Id = $('.switch-label').attr('data-id');
            var checkStatus = this.checked ? 'ON' : 'OFF    


            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateNtf", "author2")',
                data: {
                    id: 13,
                    status: checkStatus
                },
                dataType: 'json',
                success: function (result) {
                    alert(result);
                    //if (result) {

                    //    result.NTFOnOFF = checkStatus

                    //    console.log("Ok");
                    //} else {

                    //    console.log("error");
                    //}

                },
                error: function () {
                    console.log('something went wrong - debug it!');
                }
            })

        });




         jQuery.validator.addMethod('CantbothExistValidator', function (value, element, params) {
             var currentDate = new Date();
             if (Date.parse(value) > currentDate) {
                 return false;
             }
             return true;
         }, '');

         jQuery.validator.unobtrusive.adapters.add('CantbothExistValidator', function (options) {
             options.rules['CantbothExistValidator'] = {};
             options.messages['CantbothExistValidator'] = options.message;
         });

    });
    </script>
}

WebApplication1/TestApplication1/Views/author2/Index.cshtml
@model IEnumerable<TestApplication1.Models.author2>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Author_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Author_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Author_id })
            </td>
        </tr>
    }

</table>


@Html.DropDownList("hoze", new List<SelectListItem> { new SelectListItem { Text = "fani", Value = "fani " }, { new SelectListItem { Text = "sima", Value = "sima" } } },new { @onchange = "CallChangefunc(this.value)" })
@Html.DropDownList("vahed", new List<SelectListItem> { new SelectListItem { Text = "v1", Value = "v1" }, { new SelectListItem { Text = "v2", Value = "v2" } } }, htmlAttributes: new { @id = "vahed1", @name = "vahed1", @style = "display:none" })
@Html.DropDownList("vahed", new List<SelectListItem> { new SelectListItem { Text = "v3", Value = "v3" }, { new SelectListItem { Text = "v4 ", Value = "v4" } } }, htmlAttributes: new { @id = "vahed2", @name = "vahed2", @style = "display:none" })

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            if ($('#hoze option:selected').text() == "fani") {
                $("#vahed1").css('display', 'block');
            }
            else { $("#vahed2").css('display', 'block')}
        })

        function CallChangefunc(val) {
            if (val == "sima") {
                $("#vahed1").css('display', 'none');
                $("#vahed2").css('display', 'block');
            }
            else {
                $("#vahed2").css('display', 'none');
                $("#vahed1").css('display', 'block');
            }
        }
    </script>

}